### ISSUE TITLE
"NETCDF ERROR: NetCDF: Variable not found" from tropical_storms_wsfc at L331

### ISSUE THREAD

**Issue by MDTocean** [NOAA-GFDL/TCtracker#13]
The "NETCDF ERROR: NetCDF: Variable not found" error is produced when running the storms executable on line 331:
$ ./tstorms_driver < nml_input

**Comment by underwoo** [comment]
This comes from the executable built from the code in [tstorms_driver](https://github.com/NOAA-GFDL/TCtracker/tree/main/tstorms_driver).  Looking at [tstorms_driver/indata.f90](https://github.com/NOAA-GFDL/TCtracker/blob/de57e7defe4c1fb95b2c3160300e44a7eed1065b/tstorms_driver/indata.f90), the files should follow the pattern: `<pp_component>.<date_range>.<var>.nc`, where `<var>` is the name of the variable that should be contained in the file.  The following variables are needed in all cases:

* `vort850`
* `tm`
* `slp`

Unless passing the `-W` option to `tropical_storms_wsfc`, these variables are required:

* `u_ref`
* `v_ref`

If `-W` is passed, then these two variables are required instead:

* `u850`
*  `v850`

You should verify that files you reference do contain these variables.

**Comment by MDTocean** [comment]
This has worked, thank you. The problem was with the variable name, as you suspected.
